
on:
  pull_request:
    branches: ["develop"]
    
jobs:
  noti:
    runs-on: ubuntu-latest
    steps:
      - name: action-swit
        uses: roharon/action-swit@v1
        with:
          # Your Swit app's webhooks url
          webhooks_url: https://hook.swit.io/chat/23100807572852GQNW7O/FRsgpX3c9O2ziw8NcYeO?organization_id=23091405460602C84JVR
          # Message that you want
          message: 🏷 ${{ job.status }} ${{ github.sha }} - by ${{ github.actor }}

